SELECT DISTINCT  HNOPD_MASTER.HN,SUBSTRING ( dbo.HNPAT_NAME.FirstName, 2, 100 ) + ' ' + SUBSTRING ( dbo.HNPAT_NAME.LastName, 2, 100 ) AS Name,
 convert(date,HNPAT_REQFAC.VisitDate) AS LastVisitDate
 ,HNLABREQ_RESULT.LabCode,
 (SELECT ISNULL(SUBSTRING ( LocalName, 2, 1000 ), SUBSTRING ( EnglishName, 2, 1000 ))
  FROM DNSYSCONFIG 
  WHERE CtrlCode = '42136' 
  AND code = dbo.HNLABREQ_RESULT.LabCode) as LabName,
        dbo.HNLABREQ_RESULT.ResultValue

from HNOPD_MASTER

 --Left OUTER Join HNPAT_INFO on HNPAT_CHRONIC.HN = HNPAT_INFO.HN
 --Left OUTER Join HNOPD_MASTER on HNPAT_CHRONIC.HN = HNOPD_MASTER.HN
 --Left OUTER Join HNICD_MASTER on HNPAT_CHRONIC.ICDCode = HNICD_MASTER.ICDCode
 Left Join HNPAT_INFO ON HNOPD_MASTER.HN = HNPAT_INFO.HN
 Left Join HNOPD_PRESCRIP_DIAG ON HNOPD_MASTER.Vn = HNOPD_PRESCRIP_DIAG.VN and HNOPD_MASTER.VisitDate = HNOPD_PRESCRIP_DIAG.VisitDate
 Left OUTER Join HNPAT_NAME on HNOPD_MASTER.HN = HNPAT_NAME.HN
 Left OUTER Join HNOPD_PRESCRIP on HNOPD_MASTER.VisitDate = HNOPD_PRESCRIP.VisitDate and HNOPD_MASTER.VN = HNOPD_PRESCRIP.VN
 Left OUTER Join HNPAT_REQFAC on HNOPD_MASTER.HN = HNPAT_REQFAC.HN
 LEFT OUTER JOIN HNLABREQ_HEADER ON HNPAT_REQFAC.RequestNo = HNLABREQ_HEADER.RequestNo
 Left OUTER Join HNLABREQ_RESULT on HNLABREQ_HEADER.RequestNo = HNLABREQ_RESULT.RequestNo

Where HNPAT_INFO.DeadDateTime is null and HNPAT_INFO.FileDeletedDate is null
--and CONVERT(date,HNOPD_MASTER.VisitDate,23) = CONVERT(date,GETDATE(),23)
and HNPAT_NAME.SuffixSmall = 0 
--and HNOPD_PRESCRIP.DefaultRightCode = '2100'  
and HNLABREQ_RESULT.LabCode in ('C1032','C1003','CR01','C1057','C1035',' U3001','C1083','S5015','O0323','EL001','H2005','C1015','C1011','C1014','O1273','O1830','O0684')
and year (HNPAT_REQFAC.VisitDate) = year(GETDATE())
And HNLABREQ_HEADER.CxlDateTime is null
And SpecimenReceiveDateTime is not null

And HNOPD_MASTER.HN = '67-012713'
Order By HNOPD_MASTER.HN ASC